"use client";

import { useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { useRouter } from "next/navigation";

interface Vendor {
  id: string;
  establishment_name: string;
  email: string;
}

interface Props {
  contractId: string;
  vendors: Vendor[];
  label: string;
  small?: boolean;
}

export function SendContractButton({ contractId, vendors, label, small }: Props) {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [done, setDone] = useState(false);

  const handleSend = async () => {
    if (!vendors.length) return;
    setLoading(true);

    try {
      const supabase = createClient();

      // Create signature records for each vendor (token auto-generated by DB)
      const rows = vendors.map((v) => ({
        contract_id: contractId,
        vendor_id: v.id,
      }));

      const { data: inserted, error } = await supabase
        .from("vendor_contract_signatures")
        .upsert(rows, { onConflict: "contract_id,vendor_id", ignoreDuplicates: true })
        .select("token, vendor_id");

      if (error) throw error;

      // Build sign links and show them (in production: send via email API)
      const links = (inserted ?? []).map((sig) => {
        const vendor = vendors.find((v) => v.id === sig.vendor_id);
        const url = `${window.location.origin}/vendor/sign/${sig.token}`;
        return `${vendor?.establishment_name ?? sig.vendor_id}: ${url}`;
      });

      if (links.length > 0) {
        alert(
          `تم إنشاء روابط التوقيع التالية:\n\n${links.join("\n\n")}\n\nيمكنك إرسالها للموردين عبر البريد الإلكتروني.`
        );
      }

      setDone(true);
      router.refresh();
    } catch (err) {
      console.error(err);
      alert("حدث خطأ، حاول مجدداً");
    } finally {
      setLoading(false);
    }
  };

  if (small) {
    return (
      <button
        onClick={handleSend}
        disabled={loading || done}
        className="rounded-lg border border-[#1D3F1F]/15 px-2.5 py-1 text-xs font-medium text-[#1D3F1F]/70 hover:bg-[#1D3F1F]/5 disabled:opacity-40 transition-colors"
      >
        {loading ? "..." : done ? "✓" : label}
      </button>
    );
  }

  return (
    <button
      onClick={handleSend}
      disabled={loading || done}
      className="w-full rounded-lg bg-[#09B14B] py-2 text-sm font-semibold text-white hover:bg-[#09B14B]/90 disabled:opacity-50 transition-colors"
    >
      {loading ? "جارٍ الإنشاء..." : done ? "✓ تم إنشاء الروابط" : label}
    </button>
  );
}
