"use client";

import { useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { useRouter } from "next/navigation";

interface Vendor {
  id: string;
  establishment_name: string;
  email: string;
}

interface Props {
  contractId: string;
  vendors: Vendor[];
  label: string;
  small?: boolean;
}

export function SendContractButton({ contractId, vendors, label, small }: Props) {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [done, setDone] = useState(false);

  const handleSend = async () => {
    if (!vendors.length) return;
    setLoading(true);

    try {
      const supabase = createClient();

      // Create signature records for each vendor (token auto-generated by DB)
      const rows = vendors.map((v) => ({
        contract_id: contractId,
        vendor_id: v.id,
      }));

      const { data: inserted, error } = await supabase
        .from("vendor_contract_signatures")
        .upsert(rows, { onConflict: "contract_id,vendor_id", ignoreDuplicates: true })
        .select("token, vendor_id");

      if (error) throw error;

      // Fetch contract title for the email
      const supabase2 = createClient();
      const { data: contract } = await supabase2
        .from("contracts")
        .select("title")
        .eq("id", contractId)
        .single();

      // Send email to each vendor via API route
      const emailPromises = (inserted ?? []).map((sig) => {
        const vendor = vendors.find((v) => v.id === sig.vendor_id);
        if (!vendor) return Promise.resolve();
        return fetch("/api/email/contract-sign", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            establishment_name: vendor.establishment_name,
            manager_name: vendor.establishment_name,
            email: vendor.email,
            token: sig.token,
            contractTitle: contract?.title ?? "عقد الموردين",
          }),
        });
      });

      await Promise.allSettled(emailPromises);

      setDone(true);
      router.refresh();
    } catch (err) {
      console.error(err);
      alert("حدث خطأ، حاول مجدداً");
    } finally {
      setLoading(false);
    }
  };

  if (small) {
    return (
      <button
        onClick={handleSend}
        disabled={loading || done}
        className="rounded-lg border border-[#1D3F1F]/15 px-2.5 py-1 text-xs font-medium text-[#1D3F1F]/70 hover:bg-[#1D3F1F]/5 disabled:opacity-40 transition-colors"
      >
        {loading ? "..." : done ? "✓" : label}
      </button>
    );
  }

  return (
    <button
      onClick={handleSend}
      disabled={loading || done}
      className="w-full rounded-lg bg-[#09B14B] py-2 text-sm font-semibold text-white hover:bg-[#09B14B]/90 disabled:opacity-50 transition-colors"
    >
      {loading ? "جارٍ الإنشاء..." : done ? "✓ تم إنشاء الروابط" : label}
    </button>
  );
}
